1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

NumPy is a Python library used for scientific computing, data analysis, and numerical computations123. It provides the following advantages:
1. Efficient handling of arrays and matrices.
2. Faster and more efficient mathematical calculations compared to Python lists.
3. Lower memory usage.
4. Seamless integration with other libraries.
5. Core functionality for numerical operations in Python.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Both np.mean() and np.average() functions in NumPy are used to calculate the average of array elements, but they have some key differences and specific use cases:

np.mean()

Purpose:
Calculates the arithmetic mean (simple average) of the array elements.

Syntax: np.mean(arr, axis=None)

Weights: Does not support weights; all elements are considered equally.

Use Case: Use np.mean() when we need the simple arithmetic mean of an array without considering any weights.

np.average()
Purpose: Calculates the weighted average of the array elements if weights are provided; otherwise, it calculates the arithmetic mean.

Syntax: np.average(arr, axis=None, weights=None)

Weights: Supports weights; we can pass an array of weights to compute a weighted average.

Use Case: Use np.average() when we need to calculate a weighted average, where different elements contribute differently to the final average.

In [1]:
#example
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Using np.mean()
mean_value = np.mean(arr)
print("Mean:", mean_value)  # Output: Mean: 3.0

# Using np.average() without weights
average_value = np.average(arr)
print("Average:", average_value)  # Output: Average: 3.0

# Using np.average() with weights
weights = np.array([1, 2, 3, 4, 5])
weighted_average_value = np.average(arr, weights=weights)
print("Weighted Average:", weighted_average_value)

Mean: 3.0
Average: 3.0
Weighted Average: 3.6666666666666665


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Some of the most frequent methods for reversing a numpy array are as follows:

1.Utilizing the len() with Loops

2.Using the list slicing technique

3.Using the flip() function

4.Using the reverse() function

5.Using the flipud() function

6.Using the fliplr() function

In [2]:
#Example
# 1D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)
print(reversed_arr)

import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Original array
print("Original array:\n", arr)

# Reverse the array along axis 0 (rows)
reversed_rows = np.flip(arr, axis=0)
print("\nReversed along axis 0 (rows):\n", reversed_rows)

# Reverse the array along axis 1 (columns)
reversed_columns = np.flip(arr, axis=1)
print("\nReversed along axis 1 (columns):\n", reversed_columns)

# Reverse the array using slicing (rows)
sliced_rows = arr[::-1, :]
print("\nReversed rows using slicing:\n", sliced_rows)

# Reverse the array using slicing (columns)
sliced_columns = arr[:, ::-1]
print("\nReversed columns using slicing:\n", sliced_columns)

# Reverse the array using flipud (vertical flip)
flipped_ud = np.flipud(arr)
print("\nFlipped vertically using flipud:\n", flipped_ud)

# Reverse the array using fliplr (horizontal flip)
flipped_lr = np.fliplr(arr)
print("\nFlipped horizontally using fliplr:\n", flipped_lr)


[5 4 3 2 1]
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed along axis 0 (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed along axis 1 (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Reversed rows using slicing:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed columns using slicing:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Flipped vertically using flipud:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Flipped horizontally using fliplr:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [3]:
#To determine the data type of elements in a NumPy array, you can use the dtype attribute. Here’s a simple example:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Check the data type of the array elements
print(arr.dtype)

int64


Importance of Data Types in Memory Management and Performance
Data types play a crucial role in memory management and performance for several reasons:

1.Memory Efficiency: Different data types consume different amounts of memory. For example, an int32 uses 4 bytes, while an int64 uses 8 bytes. Choosing the appropriate data type can help optimize memory usage, especially when dealing with large datasets2.

2.Performance Optimization: Operations on smaller data types are generally faster because they require less memory bandwidth and can take advantage of CPU cache more effectively. For instance, using float32 instead of float64 can speed up numerical computations3.

3.Data Integrity: Proper data types ensure that the data is stored and processed correctly. For example, using an integer type for counting items prevents fractional values, which could lead to logical errors in the program4.

4.Error Detection: Using specific data types can help catch errors early in the development process. For example, trying to store a string in an integer array will raise an error, alerting the developer to a potential issue4.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

NumPy ndarrays (N-dimensional arrays) are a core data structure in the NumPy library, designed for efficient numerical computation. Here are some key features and differences compared to standard Python lists:

Key Features of NumPy ndarrays:

1.Homogeneous Data: All elements in an ndarray must be of the same data type, which allows for more efficient storage and computation1.

2.N-Dimensional: ndarrays can have multiple dimensions (e.g., 1D, 2D, 3D, etc.), making them suitable for representing complex data structures like matrices and tensors1.

3.Efficient Operations: NumPy supports vectorized operations, which means operations are applied element-wise, leading to faster execution compared to loops in standard Python lists2.

4.Broadcasting: This feature allows NumPy to perform operations on arrays of different shapes by automatically expanding them to a common shape2.

5.Memory Efficiency: ndarrays are stored in contiguous blocks of memory, which enhances performance for large datasets1.

6.Rich Functionality: NumPy provides numerous functions for array creation, manipulation, and mathematical operations, such as np.zeros, np.ones, np.full, np.empty, np.arange, and np.linspace1.

Differences from Standard Python Lists:

1.Data Type Consistency: Python lists can contain elements of different data types, whereas ndarrays require all elements to be of the same type1.

2.Performance: ndarrays are generally faster and more memory-efficient than Python lists, especially for large datasets and numerical operations1.

3.Dimensionality: While Python lists can be nested to create multi-dimensional structures, ndarrays are inherently multi-dimensional and provide more efficient and intuitive ways to handle such data1.

4.Functionality: NumPy offers a wide range of built-in functions for mathematical and statistical operations, which are not available for standard Python lists2.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

1.Homogeneous Data: NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.

2.Fixed Data Type: NumPy arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.

3.Contiguous Memory: NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.

4.Array Metadata: NumPy arrays have extra metadata like shape, strides, and data type. However, this overhead is usually smaller than the per-element overhead in lists.

5.Performance: NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [4]:
#vstack() and hstack() functions in NumPy and see how they work with some examples.

#vstack()
#Purpose: Stacks arrays in sequence vertically (row-wise).
#Usage: Useful when you want to add rows to an existing array.
#Example:

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])

result = np.vstack((a, b))
print(result)

#hstack()
#Purpose: Stacks arrays in sequence horizontally (column-wise).
#Usage: Useful when you want to add columns to an existing array.
#Example:


import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [8]])

result = np.hstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions

In [5]:
#The fliplr() and flipud() methods in NumPy are used to flip arrays, but they operate along different axes:

#fliplr():
#Function: Flips the array in the left/right direction.
#Axis: Operates along axis 1 (columns).
#Effect: Reverses the order of elements in each row, preserving the row structure.
#Example:

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.fliplr(a))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [6]:
#flipud():
#Function: Flips the array in the up/down direction.
#Axis: Operates along axis 0 (rows).
#Effect: Reverses the order of elements in each column, preserving the column structure.
#Example:

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.flipud(a))

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#Key Differences:
#Direction: fliplr() flips left/right (horizontal), while flipud() flips up/down (vertical).
#Axis: fliplr() operates on axis 1, and flipud() operates on axis 0.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The numpy.array_split() method in NumPy is used to split an array into multiple sub-arrays. This function is particularly useful when you need to divide an array into sections that may not be of equal size.

Functionality
The basic syntax of numpy.array_split() is:

numpy.array_split(ary, indices_or_sections, axis=0)

1.ary: The input array to be split.

2.indices_or_sections: If an integer, it indicates the number of equal or nearly equal sections to split the array into. If a list of sorted integers, it specifies the indices at which to split the array.

3.axis: The axis along which to split the array. The default is 0 (along rows).

In [7]:
#Handling Uneven Splits
#When the array cannot be evenly divided by the specified number of sections, numpy.array_split() handles the uneven splits by distributing the remainder among the sub-arrays
import numpy as np

# Create an array of 9 elements
x = np.arange(9)

# Split the array into 4 parts
result = np.array_split(x, 4)

print(result)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization in NumPy refers to performing operations on arrays without using explicit loops. It allows efficient element-wise operations by applying the operation to the entire array at once. This is faster than using loops.

 Broadcasting, on the other hand, is a technique that allows arithmetic operations on arrays of different shapes and sizes. It "broadcasts" the smaller array to match the shape of the larger array, enabling efficient element-wise operations. Both vectorization and broadcasting contribute to efficient array operations in NumPy by avoiding unnecessary loops and data copies.

In [11]:
#vectorization
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr * 2

print(result)


[ 2  4  6  8 10]


#practical part

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [12]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed array:")
print(transposed_array)

Original array:
[[72 16 18]
 [23 69 13]
 [44 34 23]]

Transposed array:
[[72 23 44]
 [16 69 34]
 [18 13 23]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [13]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [14]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array with random float values:\n", array_4x4)
print("\n6x6 Array with a border of zeros:\n", array_6x6)

4x4 Array with random float values:
 [[0.79212048 0.06793999 0.03035533 0.43789246]
 [0.90396128 0.94798404 0.89527076 0.57169998]
 [0.19646671 0.9392019  0.94921795 0.89744492]
 [0.80056261 0.97742385 0.46983888 0.72079301]]

6x6 Array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.79212048 0.06793999 0.03035533 0.43789246 0.        ]
 [0.         0.90396128 0.94798404 0.89527076 0.57169998 0.        ]
 [0.         0.19646671 0.9392019  0.94921795 0.89744492 0.        ]
 [0.         0.80056261 0.97742385 0.46983888 0.72079301 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [15]:
import numpy as np

array = np.arange(10, 65, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [16]:
# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title case:", titlecase_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [17]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Function to insert spaces between characters
def insert_spaces(word):
    return ' '.join(word)

# Apply the function to each word in the array
spaced_words = np.vectorize(insert_spaces)(words)

print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [18]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = np.add(array1, array2)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)

# Element-wise division
division = np.divide(array1, array2)

# Print results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [19]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [20]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random integers array:", random_integers)
print("Prime numbers in the array:", prime_numbers)

Random integers array: [ 43 857 891 842 979 697  39 181 890 973 258 651 405 244 281 918 272 530
 759 396 331 301 205 963 432 414  44 410 239 828 466 720 211 262 352 629
 284 256 812 516   8 497 295 194 334 775 368 919 786 650 408 999  87 787
  82 304 384 140 124 868 729 620  61  22 246 902 959 328 301 152 470  19
  89 446 250 711 856 576 659 109  64 198 831 411 594 307 274 840 748 128
 902 501 766 827 149 157  75  10 610 312]
Prime numbers in the array: [43, 857, 181, 281, 331, 239, 211, 919, 787, 61, 19, 89, 659, 109, 307, 827, 149, 157]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages

In [21]:
import numpy as np

# Create a NumPy array with 30 random daily temperatures for a month
daily_temperatures = np.random.randint(20, 35, size=30)  # Temperatures between 20°C and 35°C

# Calculate weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

# Display the results
print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [22 21 33 20 29 27 25 33 27 29 29 33 21 27 23 27 30 22 34 21 28 31 21 24
 29 23 20 23 28 25]
Weekly Averages: [25.285714285714285, 28.428571428571427, 26.428571428571427, 24.428571428571427, 26.5]
